FROM python:3.12.11-alpine3.22

ARG container_user=openg2p
ARG container_user_group=openg2p
ARG container_user_uid=1001
ARG container_user_gid=1001

RUN apk add --no-cache --virtual .build-deps gcc libc-dev linux-headers make
RUN apk add --no-cache bash git gettext libpq-dev

RUN addgroup -g ${container_user_gid} ${container_user_group} \
  && adduser -D -u ${container_user_uid} -G ${container_user_group} -s /bin/bash ${container_user}

WORKDIR /app

ADD openg2p-g2p-bridge-models /app/openg2p-g2p-bridge-models
ADD openg2p-g2p-bridge-bank-connectors /app/openg2p-g2p-bridge-bank-connectors
ADD openg2p-g2p-bridge-celery-workers /app/openg2p-g2p-bridge-celery-workers
RUN mv /app/openg2p-g2p-bridge-celery-workers/main.py /app

RUN pip install git+https://github.com/openg2p/openg2p-fastapi-common@1.1\#subdirectory=openg2p-fastapi-common  # to_be_removed_on_tag
RUN pip install git+https://github.com/openg2p/openg2p-g2pconnect-common-lib@1.1\#subdirectory=openg2p-g2pconnect-common-lib # to_be_removed_on_tag
RUN pip install git+https://github.com/openg2p/openg2p-g2pconnect-common-lib@1.1\#subdirectory=openg2p-g2pconnect-mapper-lib # to_be_removed_on_tag
RUN pip install \
    -e /app/openg2p-g2p-bridge-models \
    -e /app/openg2p-g2p-bridge-bank-connectors \
    -e /app/openg2p-g2p-bridge-celery-workers

RUN apk del --no-network .build-deps

USER ${container_user}

ENV PYTHONUNBUFFERED=1

CMD celery -A main.celery_app worker -Q g2p_bridge_celery_worker_tasks --loglevel=info
