import enum


class G2PBridgeErrorCodes(enum.Enum):
    # Request Validation Errors
    REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"

    # Disbursement Envelope Errors
    INVALID_PROGRAM_ID = "INVALID_PROGRAM_ID"
    INVALID_PROGRAM_MNEMONIC = "INVALID_PROGRAM_MNEMONIC"
    INVALID_DISBURSEMENT_FREQUENCY = "INVALID_DISBURSEMENT_FREQUENCY"
    INVALID_CYCLE_CODE_MNEMONIC = "INVALID_CYCLE_CODE_MNEMONIC"
    INVALID_NO_OF_BENEFICIARIES = "INVALID_NO_OF_BENEFICIARIES"
    INVALID_NO_OF_DISBURSEMENTS = "INVALID_NO_OF_DISBURSEMENTS"
    INVALID_TOTAL_DISBURSEMENT_QUANTITY = "INVALID_TOTAL_DISBURSEMENT_QUANTITY"
    INVALID_DISBURSEMENT_CURRENCY_CODE = "INVALID_DISBURSEMENT_CURRENCY_CODE"
    INVALID_DISBURSEMENT_SCHEDULE_DATE = "INVALID_DISBURSEMENT_SCHEDULE_DATE"
    DISBURSEMENT_ENVELOPE_NOT_FOUND = "DISBURSEMENT_ENVELOPE_NOT_FOUND"
    DISBURSEMENT_ENVELOPE_ALREADY_CANCELED = "DISBURSEMENT_ENVELOPE_ALREADY_CANCELED"
    INVALID_DISBURSEMENT_ENVELOPE_ID = "INVALID_DISBURSEMENT_ENVELOPE_ID"
    INVALID_DISBURSEMENT_QUANTITY = "INVALID_DISBURSEMENT_QUANTITY"
    INVALID_BENEFICIARY_ID = "INVALID_BENEFICIARY_ID"
    INVALID_BENEFICIARY_NAME = "INVALID_BENEFICIARY_NAME"
    INVALID_NARRATIVE = "INVALID_NARRATIVE"
    INVALID_RECEIPT_TIME_STAMP = "INVALID_RECEIPT_TIME_STAMP"
    INVALID_TARGET_REGISTRY = "INVALID_TARGET_REGISTRY"
    INVALID_BENEFIT_CODE_ID = "INVALID_BENEFIT_CODE_ID"
    INVALID_BENEFIT_CODE_MNEMONIC = "INVALID_BENEFIT_CODE_MNEMONIC"
    DISBURSEMENT_ENVELOPE_DATE_PASSED = "DISBURSEMENT_ENVELOPE_DATE_PASSED"

    # Disbursement Errors
    INVALID_DISBURSEMENT_ID = "INVALID_DISBURSEMENT_ID"
    INVALID_RECONCILIATION_ID = "INVALID_RECONCILIATION_ID"
    INVALID_DISBURSEMENT_PAYLOAD = "INVALID_DISBURSEMENT_PAYLOAD"
    ENVELOPE_ALREADY_CANCELLED = "ENVELOPE_ALREADY_CANCELLED"
    NO_OF_DISBURSEMENTS_EXCEEDS_DECLARED = "NO_OF_DISBUESEMENTS_EXCEEDS_DECLARED"
    NO_OF_DISBURSEMENTS_LESS_THAN_ZERO = "NO_OF_DISBURSEMENTS_LESS_THAN_ZERO"
    TOTAL_DISBURSEMENT_QUANTITY_EXCEEDS_DECLARED = "TOTAL_DISBURSEMENT_QUANTITY_EXCEEDS_DECLARED"
    TOTAL_DISBURSEMENT_QUANTITY_LESS_THAN_ZERO = "TOTAL_DISBURSEMENT_QUANTITY_LESS_THAN_ZERO"
    MULTIPLE_ENVELOPES_FOUND = "MULTIPLE_ENVELOPES_FOUND"
    DISBURSEMENT_ENVELOPE_SCHEDULE_DATE_REACHED = "DISBURSEMENT_ENVELOPE_SCHEDULE_DATE_REACHED"
    DISBURSEMENT_ALREADY_CANCELED = "DISBURSEMENT_ALREADY_CANCELED"

    # Account Statement Errors
    STATEMENT_UPLOAD_ERROR = "STATEMENT_UPLOAD_ERROR"

    # Disbursement Recon Errors
    DUPLICATE_DISBURSEMENT = "DUPLICATE_DISBURSEMENT"
    INVALID_REVERSAL = "INVALID_REVERSAL"
    INVALID_ACCOUNT_NUMBER = "INVALID_ACCOUNT_NUMBER"

    # Database Errors
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR"
    DATABASE_TRANSACTION_ERROR = "DATABASE_TRANSACTION_ERROR"


class G2PBridgeStatusReasonCodeEnum(enum.Enum):

    rjct_version_invalid = "rjct.version.invalid"
    rjct_message_id_duplicate = "rjct.message_id.duplicate"
    rjct_message_ts_invalid = "rjct.message_ts.invalid"
    rjct_action_invalid = "rjct.action.invalid"
    rjct_action_not_supported = "rjct.action.not_supported"
    rjct_total_count_invalid = "rjct.total_count.invalid"
    rjct_total_count_limit_exceeded = "rjct.total_count.limit_exceeded"
    rjct_errors_too_many = "rjct.errors.too_many"
    rjct_jwt_invalid = "rjct.jwt.invalid"
    rjct_file_size_exceeded = "rjct.file.size.exceeded"
    rjct_file_type_invalid = "rjct.file.type.invalid"
    rjct_virus_check_failed = "rjct.virus.check.failed"
